version: '3'

services:
  # Database
  db:
    networks:
      - wpdbnet
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
      MYSQL_USER: monuser
      MYSQL_PASSWORD: monpass
  # phpmyadmin
  phpmyadmin:
    networks :
      - wpdbnet
      - default
    links:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password 
  # Wordpress
  wordpress:
    networks :
       - default
       - wpdbnet
    image: wordpress:latest
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: monuser
      WORDPRESS_DB_PASSWORD: monpass
      WORDPRESS_DB_NAME: db
  nginx:
     build: nginx-proxy/
     ports:
       - '8080:80'
     links:
       - sitea
       - siteb
       - wordpress
       - phpmyadmin
       - sitec
  sitea:
     build: siteA/
  siteb:
     build: siteB/
  sitec1:
     build: siteC1/
  sitec2:
     build: siteC2/
  sitec:
     build: load-balancer/
     links :
       - sitec1
       - sitec2
           
networks:
     wpdbnet:
