version: '3'

services:
  # Database
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
      MYSQL_USER: monuser
      MYSQL_PASSWORD: monpass
  # phpmyadmin
  phpmyadmin:
    links:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8000:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password 
  # Wordpress
  wordpress:
    image: wordpress:latest
    ports:
      - '8080:80'
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: monuser
      WORDPRESS_DB_PASSWORD: monpass
      WORDPRESS_DB_NAME: db
